// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/backforge-app/backforge/internal/transport/http/handler/auth (interfaces: Service,Responder)

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	http "net/http"
	reflect "reflect"

	auth "github.com/backforge-app/backforge/internal/service/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// LoginWithTelegram mocks base method.
func (m *MockService) LoginWithTelegram(arg0 context.Context, arg1 auth.TelegramLoginInput) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithTelegram", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginWithTelegram indicates an expected call of LoginWithTelegram.
func (mr *MockServiceMockRecorder) LoginWithTelegram(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithTelegram", reflect.TypeOf((*MockService)(nil).LoginWithTelegram), arg0, arg1)
}

// RefreshTokens mocks base method.
func (m *MockService) RefreshTokens(arg0 context.Context, arg1 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockServiceMockRecorder) RefreshTokens(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockService)(nil).RefreshTokens), arg0, arg1)
}

// MockResponder is a mock of Responder interface.
type MockResponder struct {
	ctrl     *gomock.Controller
	recorder *MockResponderMockRecorder
}

// MockResponderMockRecorder is the mock recorder for MockResponder.
type MockResponderMockRecorder struct {
	mock *MockResponder
}

// NewMockResponder creates a new mock instance.
func NewMockResponder(ctrl *gomock.Controller) *MockResponder {
	mock := &MockResponder{ctrl: ctrl}
	mock.recorder = &MockResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponder) EXPECT() *MockResponderMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockResponder) Error(arg0 http.ResponseWriter, arg1 int, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", arg0, arg1, arg2)
}

// Error indicates an expected call of Error.
func (mr *MockResponderMockRecorder) Error(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockResponder)(nil).Error), arg0, arg1, arg2)
}

// Message mocks base method.
func (m *MockResponder) Message(arg0 http.ResponseWriter, arg1 int, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Message", arg0, arg1, arg2)
}

// Message indicates an expected call of Message.
func (mr *MockResponderMockRecorder) Message(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockResponder)(nil).Message), arg0, arg1, arg2)
}
