// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/backforge-app/backforge/internal/service/progress (interfaces: UserQuestionProgressRepository,UserTopicProgressRepository)

// Package progress is a generated GoMock package.
package progress

import (
	context "context"
	reflect "reflect"

	domain "github.com/backforge-app/backforge/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserQuestionProgressRepository is a mock of UserQuestionProgressRepository interface.
type MockUserQuestionProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserQuestionProgressRepositoryMockRecorder
}

// MockUserQuestionProgressRepositoryMockRecorder is the mock recorder for MockUserQuestionProgressRepository.
type MockUserQuestionProgressRepositoryMockRecorder struct {
	mock *MockUserQuestionProgressRepository
}

// NewMockUserQuestionProgressRepository creates a new mock instance.
func NewMockUserQuestionProgressRepository(ctrl *gomock.Controller) *MockUserQuestionProgressRepository {
	mock := &MockUserQuestionProgressRepository{ctrl: ctrl}
	mock.recorder = &MockUserQuestionProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQuestionProgressRepository) EXPECT() *MockUserQuestionProgressRepositoryMockRecorder {
	return m.recorder
}

// GetByUserAndQuestion mocks base method.
func (m *MockUserQuestionProgressRepository) GetByUserAndQuestion(arg0 context.Context, arg1, arg2 uuid.UUID) (*domain.UserQuestionProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndQuestion", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.UserQuestionProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndQuestion indicates an expected call of GetByUserAndQuestion.
func (mr *MockUserQuestionProgressRepositoryMockRecorder) GetByUserAndQuestion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndQuestion", reflect.TypeOf((*MockUserQuestionProgressRepository)(nil).GetByUserAndQuestion), arg0, arg1, arg2)
}

// ListByUserAndTopic mocks base method.
func (m *MockUserQuestionProgressRepository) ListByUserAndTopic(arg0 context.Context, arg1, arg2 uuid.UUID) ([]*domain.UserQuestionProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserAndTopic", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.UserQuestionProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserAndTopic indicates an expected call of ListByUserAndTopic.
func (mr *MockUserQuestionProgressRepositoryMockRecorder) ListByUserAndTopic(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserAndTopic", reflect.TypeOf((*MockUserQuestionProgressRepository)(nil).ListByUserAndTopic), arg0, arg1, arg2)
}

// ResetByTopic mocks base method.
func (m *MockUserQuestionProgressRepository) ResetByTopic(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetByTopic", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetByTopic indicates an expected call of ResetByTopic.
func (mr *MockUserQuestionProgressRepositoryMockRecorder) ResetByTopic(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetByTopic", reflect.TypeOf((*MockUserQuestionProgressRepository)(nil).ResetByTopic), arg0, arg1, arg2)
}

// SetStatus mocks base method.
func (m *MockUserQuestionProgressRepository) SetStatus(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 domain.ProgressStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockUserQuestionProgressRepositoryMockRecorder) SetStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockUserQuestionProgressRepository)(nil).SetStatus), arg0, arg1, arg2, arg3)
}

// MockUserTopicProgressRepository is a mock of UserTopicProgressRepository interface.
type MockUserTopicProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserTopicProgressRepositoryMockRecorder
}

// MockUserTopicProgressRepositoryMockRecorder is the mock recorder for MockUserTopicProgressRepository.
type MockUserTopicProgressRepositoryMockRecorder struct {
	mock *MockUserTopicProgressRepository
}

// NewMockUserTopicProgressRepository creates a new mock instance.
func NewMockUserTopicProgressRepository(ctrl *gomock.Controller) *MockUserTopicProgressRepository {
	mock := &MockUserTopicProgressRepository{ctrl: ctrl}
	mock.recorder = &MockUserTopicProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTopicProgressRepository) EXPECT() *MockUserTopicProgressRepositoryMockRecorder {
	return m.recorder
}

// GetByUserAndTopic mocks base method.
func (m *MockUserTopicProgressRepository) GetByUserAndTopic(arg0 context.Context, arg1, arg2 uuid.UUID) (*domain.UserTopicProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndTopic", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.UserTopicProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndTopic indicates an expected call of GetByUserAndTopic.
func (mr *MockUserTopicProgressRepositoryMockRecorder) GetByUserAndTopic(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndTopic", reflect.TypeOf((*MockUserTopicProgressRepository)(nil).GetByUserAndTopic), arg0, arg1, arg2)
}

// ResetByTopic mocks base method.
func (m *MockUserTopicProgressRepository) ResetByTopic(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetByTopic", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetByTopic indicates an expected call of ResetByTopic.
func (mr *MockUserTopicProgressRepositoryMockRecorder) ResetByTopic(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetByTopic", reflect.TypeOf((*MockUserTopicProgressRepository)(nil).ResetByTopic), arg0, arg1, arg2)
}

// SetPosition mocks base method.
func (m *MockUserTopicProgressRepository) SetPosition(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPosition", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPosition indicates an expected call of SetPosition.
func (mr *MockUserTopicProgressRepositoryMockRecorder) SetPosition(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPosition", reflect.TypeOf((*MockUserTopicProgressRepository)(nil).SetPosition), arg0, arg1, arg2, arg3)
}
