/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as QuestionsSlugRouteImport } from './routes/questions.$slug'

const IndexLazyRouteImport = createFileRoute('/')()
const TopicsIndexLazyRouteImport = createFileRoute('/topics/')()
const QuestionsIndexLazyRouteImport = createFileRoute('/questions/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TopicsIndexLazyRoute = TopicsIndexLazyRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/topics.index.lazy').then((d) => d.Route))
const QuestionsIndexLazyRoute = QuestionsIndexLazyRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/questions.index.lazy').then((d) => d.Route),
)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsSlugRoute = QuestionsSlugRouteImport.update({
  id: '/questions/$slug',
  path: '/questions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/questions/': typeof QuestionsIndexLazyRoute
  '/topics/': typeof TopicsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/questions': typeof QuestionsIndexLazyRoute
  '/topics': typeof TopicsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/questions/': typeof QuestionsIndexLazyRoute
  '/topics/': typeof TopicsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questions/$slug'
    | '/topics/$slug'
    | '/questions/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/questions/$slug' | '/topics/$slug' | '/questions' | '/topics'
  id:
    | '__root__'
    | '/'
    | '/questions/$slug'
    | '/topics/$slug'
    | '/questions/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  QuestionsSlugRoute: typeof QuestionsSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  QuestionsIndexLazyRoute: typeof QuestionsIndexLazyRoute
  TopicsIndexLazyRoute: typeof TopicsIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$slug': {
      id: '/questions/$slug'
      path: '/questions/$slug'
      fullPath: '/questions/$slug'
      preLoaderRoute: typeof QuestionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  QuestionsSlugRoute: QuestionsSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  QuestionsIndexLazyRoute: QuestionsIndexLazyRoute,
  TopicsIndexLazyRoute: TopicsIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
