// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/backforge-app/backforge/internal/transport/http/handler/analytics (interfaces: Service)

// Package analytics is a generated GoMock package.
package analytics

import (
	context "context"
	reflect "reflect"

	domain "github.com/backforge-app/backforge/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetOverallProgress mocks base method.
func (m *MockService) GetOverallProgress(arg0 context.Context, arg1 uuid.UUID) (*domain.OverallProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverallProgress", arg0, arg1)
	ret0, _ := ret[0].(*domain.OverallProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverallProgress indicates an expected call of GetOverallProgress.
func (mr *MockServiceMockRecorder) GetOverallProgress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverallProgress", reflect.TypeOf((*MockService)(nil).GetOverallProgress), arg0, arg1)
}

// GetProgressByTopicPercent mocks base method.
func (m *MockService) GetProgressByTopicPercent(arg0 context.Context, arg1 uuid.UUID) ([]*domain.TopicProgressPercent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgressByTopicPercent", arg0, arg1)
	ret0, _ := ret[0].([]*domain.TopicProgressPercent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgressByTopicPercent indicates an expected call of GetProgressByTopicPercent.
func (mr *MockServiceMockRecorder) GetProgressByTopicPercent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgressByTopicPercent", reflect.TypeOf((*MockService)(nil).GetProgressByTopicPercent), arg0, arg1)
}

// ResetAllProgress mocks base method.
func (m *MockService) ResetAllProgress(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAllProgress", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAllProgress indicates an expected call of ResetAllProgress.
func (mr *MockServiceMockRecorder) ResetAllProgress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAllProgress", reflect.TypeOf((*MockService)(nil).ResetAllProgress), arg0, arg1)
}
