// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/backforge-app/backforge/internal/transport/http/handler/progress (interfaces: Service)

// Package progress is a generated GoMock package.
package progress

import (
	context "context"
	reflect "reflect"

	domain "github.com/backforge-app/backforge/internal/domain"
	progress "github.com/backforge-app/backforge/internal/service/progress"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetByTopic mocks base method.
func (m *MockService) GetByTopic(arg0 context.Context, arg1, arg2 uuid.UUID) (*domain.TopicProgressAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTopic", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.TopicProgressAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTopic indicates an expected call of GetByTopic.
func (mr *MockServiceMockRecorder) GetByTopic(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTopic", reflect.TypeOf((*MockService)(nil).GetByTopic), arg0, arg1, arg2)
}

// GetByUserAndQuestion mocks base method.
func (m *MockService) GetByUserAndQuestion(arg0 context.Context, arg1, arg2 uuid.UUID) (*domain.UserQuestionProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndQuestion", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.UserQuestionProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndQuestion indicates an expected call of GetByUserAndQuestion.
func (mr *MockServiceMockRecorder) GetByUserAndQuestion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndQuestion", reflect.TypeOf((*MockService)(nil).GetByUserAndQuestion), arg0, arg1, arg2)
}

// MarkKnown mocks base method.
func (m *MockService) MarkKnown(arg0 context.Context, arg1 progress.MarkQuestionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKnown", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkKnown indicates an expected call of MarkKnown.
func (mr *MockServiceMockRecorder) MarkKnown(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKnown", reflect.TypeOf((*MockService)(nil).MarkKnown), arg0, arg1)
}

// MarkLearned mocks base method.
func (m *MockService) MarkLearned(arg0 context.Context, arg1 progress.MarkQuestionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkLearned", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkLearned indicates an expected call of MarkLearned.
func (mr *MockServiceMockRecorder) MarkLearned(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkLearned", reflect.TypeOf((*MockService)(nil).MarkLearned), arg0, arg1)
}

// MarkSkipped mocks base method.
func (m *MockService) MarkSkipped(arg0 context.Context, arg1 progress.MarkQuestionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSkipped", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSkipped indicates an expected call of MarkSkipped.
func (mr *MockServiceMockRecorder) MarkSkipped(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSkipped", reflect.TypeOf((*MockService)(nil).MarkSkipped), arg0, arg1)
}

// ResetTopicProgress mocks base method.
func (m *MockService) ResetTopicProgress(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetTopicProgress", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetTopicProgress indicates an expected call of ResetTopicProgress.
func (mr *MockServiceMockRecorder) ResetTopicProgress(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetTopicProgress", reflect.TypeOf((*MockService)(nil).ResetTopicProgress), arg0, arg1, arg2)
}
