// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/backforge-app/backforge/internal/service/analytics (interfaces: Repository,UserQuestionProgressRepository,UserTopicProgressRepository)

// Package analytics is a generated GoMock package.
package analytics

import (
	context "context"
	reflect "reflect"

	domain "github.com/backforge-app/backforge/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetOverallProgress mocks base method.
func (m *MockRepository) GetOverallProgress(arg0 context.Context, arg1 uuid.UUID) (*domain.OverallProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverallProgress", arg0, arg1)
	ret0, _ := ret[0].(*domain.OverallProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverallProgress indicates an expected call of GetOverallProgress.
func (mr *MockRepositoryMockRecorder) GetOverallProgress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverallProgress", reflect.TypeOf((*MockRepository)(nil).GetOverallProgress), arg0, arg1)
}

// GetTopicProgressPercent mocks base method.
func (m *MockRepository) GetTopicProgressPercent(arg0 context.Context, arg1 uuid.UUID) ([]*domain.TopicProgressPercent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicProgressPercent", arg0, arg1)
	ret0, _ := ret[0].([]*domain.TopicProgressPercent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicProgressPercent indicates an expected call of GetTopicProgressPercent.
func (mr *MockRepositoryMockRecorder) GetTopicProgressPercent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicProgressPercent", reflect.TypeOf((*MockRepository)(nil).GetTopicProgressPercent), arg0, arg1)
}

// MockUserQuestionProgressRepository is a mock of UserQuestionProgressRepository interface.
type MockUserQuestionProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserQuestionProgressRepositoryMockRecorder
}

// MockUserQuestionProgressRepositoryMockRecorder is the mock recorder for MockUserQuestionProgressRepository.
type MockUserQuestionProgressRepositoryMockRecorder struct {
	mock *MockUserQuestionProgressRepository
}

// NewMockUserQuestionProgressRepository creates a new mock instance.
func NewMockUserQuestionProgressRepository(ctrl *gomock.Controller) *MockUserQuestionProgressRepository {
	mock := &MockUserQuestionProgressRepository{ctrl: ctrl}
	mock.recorder = &MockUserQuestionProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQuestionProgressRepository) EXPECT() *MockUserQuestionProgressRepositoryMockRecorder {
	return m.recorder
}

// ResetAll mocks base method.
func (m *MockUserQuestionProgressRepository) ResetAll(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAll indicates an expected call of ResetAll.
func (mr *MockUserQuestionProgressRepositoryMockRecorder) ResetAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAll", reflect.TypeOf((*MockUserQuestionProgressRepository)(nil).ResetAll), arg0, arg1)
}

// MockUserTopicProgressRepository is a mock of UserTopicProgressRepository interface.
type MockUserTopicProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserTopicProgressRepositoryMockRecorder
}

// MockUserTopicProgressRepositoryMockRecorder is the mock recorder for MockUserTopicProgressRepository.
type MockUserTopicProgressRepositoryMockRecorder struct {
	mock *MockUserTopicProgressRepository
}

// NewMockUserTopicProgressRepository creates a new mock instance.
func NewMockUserTopicProgressRepository(ctrl *gomock.Controller) *MockUserTopicProgressRepository {
	mock := &MockUserTopicProgressRepository{ctrl: ctrl}
	mock.recorder = &MockUserTopicProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTopicProgressRepository) EXPECT() *MockUserTopicProgressRepositoryMockRecorder {
	return m.recorder
}

// ResetAll mocks base method.
func (m *MockUserTopicProgressRepository) ResetAll(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAll indicates an expected call of ResetAll.
func (mr *MockUserTopicProgressRepositoryMockRecorder) ResetAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAll", reflect.TypeOf((*MockUserTopicProgressRepository)(nil).ResetAll), arg0, arg1)
}
